spring.application.name=ebank-bot
# Configuration Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2
spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false
server.port=8058
